<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Barryvdh\DomPDF\Facade\Pdf;

class TestDomPDF extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:test-dom-pdf';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Test DomPDF functionality';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('Testing DomPDF...');

        try {
            $pdf = Pdf::loadHTML('<h1>Test PDF</h1><p>This is a test PDF generated by DomPDF.</p>');
            $this->info('PDF created successfully!');

            // Save to storage for testing
            $pdf->save(storage_path('app/test.pdf'));
            $this->info('PDF saved to storage/app/test.pdf');
        } catch (\Exception $e) {
            $this->error('Error: ' . $e->getMessage());
        }
    }
}
