<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'nik' => '1',
                'name' => 'super admin',
                'email' => 'admin@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'super_admin',
                'gender' => null,
                'status' => 'approved',
                'division_id' => null,
                'position_id' => null,
                'office_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'AP000000001',
                'name' => 'ahmad direksi',
                'email' => 'direksi@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'direksi',
                'gender' => 'L',
                'status' => 'approved',
                'division_id' => 1,
                'position_id' => 11,
                'office_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'AP000000002',
                'name' => 'siti hrd',
                'email' => 'hrd@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'hrd',
                'gender' => 'P',
                'status' => 'approved',
                'division_id' => 4,
                'position_id' => 15,
                'office_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'AP000000003',
                'name' => 'budi staff apuppt',
                'email' => 'staff@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'gender' => 'L',
                'status' => 'approved',
                'division_id' => 3,
                'position_id' => 20,
                'office_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'AP000000004',
                'name' => 'rina staff apuppt kediri',
                'email' => 'staff2@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'gender' => 'P',
                'status' => 'approved',
                'division_id' => 3,
                'position_id' => 20,
                'office_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'AP000000005',
                'name' => 'joko kasie marketing',
                'email' => 'kasie@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'kasie',
                'gender' => 'L',
                'status' => 'approved',
                'division_id' => 3,
                'position_id' => 5,
                'office_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'AP000000006',
                'name' => 'dewi kabag apuppt',
                'email' => 'kabag@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'kabag-pincab',
                'gender' => 'P',
                'status' => 'approved',
                'division_id' => 3,
                'position_id' => 19,
                'office_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'AP000000007',
                'name' => 'eko staff operasional',
                'email' => 'eko@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'gender' => 'L',
                'status' => 'approved',
                'division_id' => 1,
                'position_id' => 2,
                'office_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'AP000000008',
                'name' => 'maya kasie it',
                'email' => 'maya@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'kasie',
                'gender' => 'P',
                'status' => 'approved',
                'division_id' => 1,
                'position_id' => 13,
                'office_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'AP000000009',
                'name' => 'rudi kabag operasional',
                'email' => 'rudi@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'kabag-pincab',
                'gender' => 'L',
                'status' => 'approved',
                'division_id' => 1,
                'position_id' => 12,
                'office_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'AP000000010',
                'name' => 'lina staff skai',
                'email' => 'lina@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'gender' => 'P',
                'status' => 'approved',
                'division_id' => 2,
                'position_id' => 22,
                'office_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'AP000000011',
                'name' => 'tono kabag skai',
                'email' => 'tono@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'kabag-pincab',
                'gender' => 'L',
                'status' => 'approved',
                'division_id' => 2,
                'position_id' => 21,
                'office_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'AP000000012',
                'name' => 'sari staff umum',
                'email' => 'sari@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'gender' => 'P',
                'status' => 'approved',
                'division_id' => 5,
                'position_id' => 16,
                'office_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'AP000000013',
                'name' => 'agus kasie collection',
                'email' => 'agus@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'kasie',
                'gender' => 'L',
                'status' => 'approved',
                'division_id' => 1,
                'position_id' => 6,
                'office_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'AP000000014',
                'name' => 'nina account officer',
                'email' => 'nina@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'gender' => 'P',
                'status' => 'approved',
                'division_id' => 1,
                'position_id' => 7,
                'office_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'AP000000015',
                'name' => 'hadi driver',
                'email' => 'hadi@cutiapp.com',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'gender' => 'L',
                'status' => 'approved',
                'division_id' => 5,
                'position_id' => 17,
                'office_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
